AGET(XClientMessageEvent,Addr,ev,data)
AGET(XFontStruct,HT(XCharStruct),fs,max_bounds)
AGET(XFontStruct,HT(XCharStruct),fs,min_bounds)
CCONST(AF_INET)
CCONST(AnyButton)
CCONST(BitmapSuccess)
CCONST(EAGAIN)
CCONST(EINTR)
CCONST(InputHint)
CCONST(LSBFirst)
CCONST(None)
CCONST(SOCK_STREAM)
CCONST(SelectionNotify)
CCONST(USPosition)
CINDEX(char)
CINDEX(long)
CINDEX(short)
CWORD32(CWBackPixel)
CWORD32(CWBackPixmap)
CWORD32(CWBackingStore)
CWORD32(CWBitGravity)
CWORD32(CWBorderPixel)
CWORD32(CWBorderPixmap)
CWORD32(CWBorderWidth)
CWORD32(CWCursor)
CWORD32(CWDontPropagate)
CWORD32(CWEventMask)
CWORD32(CWHeight)
CWORD32(CWOverrideRedirect)
CWORD32(CWSaveUnder)
CWORD32(CWStackMode)
CWORD32(CWWidth)
CWORD32(CWWinGravity)
CWORD32(CWX)
CWORD32(CWY)
CWORD32(GCBackground)
CWORD32(GCCapStyle)
CWORD32(GCJoinStyle)
CWORD32(GCFillStyle)
CWORD32(GCFont)
CWORD32(GCForeground)
CWORD32(GCFunction)
CWORD32(GCGraphicsExposures)
CWORD32(GCLineStyle)
CWORD32(GCLineWidth)
CWORD32(GCStipple)
CWORD32(GCSubwindowMode)
CWORD32(GCTile)
GET(Visual,Int,cv,bits_per_rgb)
GET(Visual,Int,cv,blue_mask)
GET(Visual,Int,cv,class)
GET(Visual,Int,cv,green_mask)
GET(Visual,Int,cv,map_entries)
GET(Visual,Int,cv,red_mask)
GET(Visual,VisualID,cv,visualid)
GET(XAnyEvent,Int,ev,type)
GET(XAnyEvent,WindowId,ev,window)
GET(XButtonEvent,Int,ev,button)
GET(XButtonEvent,Int,ev,state)
GET(XButtonEvent,Int,ev,x)
GET(XButtonEvent,Int,ev,x_root)
GET(XButtonEvent,Int,ev,y)
GET(XButtonEvent,Int,ev,y_root)
GET(XButtonEvent,Time,ev,time)
GET(XCharStruct,Int,cs,ascent)
GET(XCharStruct,Int,cs,descent)
GET(XCharStruct,Int,cs,lbearing)
GET(XCharStruct,Int,cs,rbearing)
GET(XCharStruct,Int,cs,width)
GET(XFontProp,Atom,fp,name)
GET(XFontProp,Int,fp,card32)
GET(XClientMessageEvent,Atom,ev,message_type)
GET(XClientMessageEvent,Int,ev,format)
GET(XColor,Int,xcol,blue)
GET(XColor,Int,xcol,green)
GET(XColor,Int,xcol,red)
GET(XColor,Word,xcol,pixel)
GET(XConfigureEvent,Int,ev,border_width)
GET(XConfigureEvent,Int,ev,height)
GET(XConfigureEvent,Int,ev,width)
GET(XConfigureEvent,Int,ev,x)
GET(XConfigureEvent,Int,ev,y)
GET(XCrossingEvent,Int,ev,detail)
GET(XCrossingEvent,Int,ev,focus)
GET(XCrossingEvent,Int,ev,mode)
GET(XCrossingEvent,Int,ev,x)
GET(XCrossingEvent,Int,ev,x_root)
GET(XCrossingEvent,Int,ev,y)
GET(XCrossingEvent,Int,ev,y_root)
GET(XCrossingEvent,Time,ev,time)
GET(XExposeEvent,Int,ev,count)
GET(XExposeEvent,Int,ev,height)
GET(XExposeEvent,Int,ev,width)
GET(XExposeEvent,Int,ev,x)
GET(XExposeEvent,Int,ev,y)
GET(XFocusChangeEvent,Int,ev,detail)
GET(XFocusChangeEvent,Int,ev,mode)
GET(XFontStruct,Char,fs,default_char)
GET(XFontStruct,HT(XCharStruct),fs,per_char)
GET(XFontStruct,HT(XFontProp),fs,properties)
GET(XFontStruct,Int,fs,all_chars_exist)
GET(XFontStruct,Int,fs,ascent)
GET(XFontStruct,Int,fs,descent)
GET(XFontStruct,Int,fs,direction)
GET(XFontStruct,XID,fs,fid)
GET(XFontStruct,Int,fs,max_byte1)
GET(XFontStruct,Int,fs,max_char_or_byte2)
GET(XFontStruct,Int,fs,min_byte1)
GET(XFontStruct,Int,fs,min_char_or_byte2)
GET(XFontStruct,Int,fs,n_properties)
GET(XGraphicsExposeEvent,Int,ev,count)
GET(XGraphicsExposeEvent,Int,ev,height)
GET(XGraphicsExposeEvent,Int,ev,major_code)
GET(XGraphicsExposeEvent,Int,ev,minor_code)
GET(XGraphicsExposeEvent,Int,ev,width)
GET(XGraphicsExposeEvent,Int,ev,x)
GET(XGraphicsExposeEvent,Int,ev,y)
GET(XKeyEvent,Int,ev,keycode)
GET(XKeyEvent,Int,ev,state)
GET(XKeyEvent,Int,ev,x)
GET(XKeyEvent,Int,ev,x_root)
GET(XKeyEvent,Int,ev,y)
GET(XKeyEvent,Int,ev,y_root)
GET(XKeyEvent,Time,ev,time)
GET(XMapEvent,WindowId,ev,window)
GET(XMotionEvent,Int,ev,state)
GET(XMotionEvent,Int,ev,x)
GET(XMotionEvent,Int,ev,x_root)
GET(XMotionEvent,Int,ev,y)
GET(XMotionEvent,Int,ev,y_root)
GET(XMotionEvent,Time,ev,time)
GET(XResizeRequestEvent,Int,ev,height)
GET(XResizeRequestEvent,Int,ev,width)
GET(XSelectionClearEvent,Atom,ev,selection)
GET(XSelectionEvent,Atom,ev,property)
GET(XSelectionEvent,Atom,ev,selection)
GET(XSelectionEvent,Atom,ev,target)
GET(XSelectionEvent,Time,ev,time)
GET(XSelectionRequestEvent,Atom,ev,property)
GET(XSelectionRequestEvent,Atom,ev,selection)
GET(XSelectionRequestEvent,Atom,ev,target)
GET(XSelectionRequestEvent,Time,ev,time)
GET(XSelectionRequestEvent,WindowId,ev,requestor)
GET(XVisibilityEvent,Int,ev,state)
GET(timeVal,Int,now,tv_sec)
GET(timeVal,Int,now,tv_usec)
GETC(sockAddr,char *,CString,sa,sa_data)
INDEX(XCharStruct)
INDEX(XFontProp)
SET(XAnyEvent,Window,xe,window,w::Window)
SET(XClassHint,CString,class_hints,res_class,rc)
SET(XClassHint,CString,class_hints,res_name,rn)
SET(XColor,Int,color,blue,blue)
SET(XColor,Int,color,green,green)
SET(XColor,Int,color,red,red)
SET(XColor,Word,c,pixel,px)
SET(XGCValues,Int,gcv,background,toC p)
SET(XGCValues,Int,gcv,cap_style,fromEnum s)
SET(XGCValues,Int,gcv,join_style,fromEnum s)
SET(XGCValues,Int,gcv,fill_style,fromEnum f)
SET(XGCValues,XID,gcv,font,toXID f)
SET(XGCValues,Int,gcv,foreground,toC p)
SET(XGCValues,Int,gcv,function,fromEnum f)
SET(XGCValues,Int,gcv,graphics_exposures, fromEnum g)
SET(XGCValues,Int,gcv,line_style,fromEnum s)
SET(XGCValues,Int,gcv,line_width,w)
SET(XGCValues,XID,gcv,stipple,toXID p)
SET(XGCValues,Int,gcv,subwindow_mode,fromEnum m)
SET(XGCValues,XID,gcv,tile,toXID p)
SET(XSelectionEvent,Atom,xe,property, props)
SET(XSelectionEvent,Atom,xe,selection, sel)
SET(XSelectionEvent,Atom,xe,target, target)
SET(XSelectionEvent,Int,xe,type,CCONST(SelectionNotify)::Int)
SET(XSelectionEvent,Time,xe,time,time)
SET(XSizeHints,Int,h,flags,CCONST(USPosition)::Int)
SET(XSizeHints,Int,h,x,x)
SET(XSizeHints,Int,h,y,y)
SET(XWMHints,Int,h,flags,CCONST(InputHint)::Int)
SET(XWMHints,Int,h,input,toC i)
SET(XWindowChanges,Int,s,border_width,w)
SET(XWindowChanges,Int,s,height,h)
SET(XWindowChanges,Int,s,stack_mode,toC sm)
SET(XWindowChanges,Int,s,width,w)
SET(XWindowChanges,Int,s,x,x)
SET(XWindowChanges,Int,s,y,y)
SET(timeVal,Int,timeout,tv_sec,(tleft `div` 1000))
SET(timeVal,Int,timeout,tv_usec,(tleft `mod` 1000) * 1000)
SETI(XPoint,Int,xpoints,i,x,x)
SETI(XPoint,Int,xpoints,i,y,y)
SETI(XRectangle,Int,rsa,i,height,h)
SETI(XRectangle,Int,rsa,i,width,w)
SETI(XRectangle,Int,rsa,i,x,x)
SETI(XRectangle,Int,rsa,i,y,y)
SETI(XdbeSwapInfo,Int,si,i,swap_action,fromEnum sa)
SETI(XdbeSwapInfo,WindowId,si,i,swap_window,wi)
SETWa(swa,background_pixel,toC p)
SETWaXID(swa,background_pixmap,toXID p)
SETWa(swa,backing_store,toC bs)
SETWa(swa,bit_gravity,toC g)
SETWa(swa,border_pixel,toC p)
SETWaXID(swa,border_pixmap,toC p)
SETWaXID(swa,cursor,toXID c)
SETWa(swa,do_not_propagate_mask,toC em)
SETWa(swa,event_mask,toC em)
SETWa(swa,override_redirect,toC b)
SETWa(swa,save_under,toC b)
SETWa(swa,win_gravity,toC g)
SINDEX(char,imgdata,i::Int,p::Int)
